### ISSUE TITLE
error in parse, DESCRIPTION file ,while installing the package from github 

### ISSUE THREAD

**Issue by rganesh** [richierocks/pathological#2]
While installing from github I get the following error, pointing to the comma at the end of the text.
- installing _source_ package 'pathological' ...
  Error in parse(text = x) : <text>:2:29: unexpected ','
  1: person("Richard", "Cotton", role = c("aut", "cre"), email =
  2:     "richierocks@gmail.com"),

**Comment by richierocks** [comment]
Thanks, that was a silly bug.  Should be fixed now.

On 12 May 2014 12:55, rganesh notifications@github.com wrote:

> While installing from github I get the following error, pointing to the
> comma at the end of the text.
> - installing _source_ package 'pathological' ... Error in parse(text =
>   x) : :2:29: unexpected ',' 1: person("Richard", "Cotton", role = c("aut",
>   "cre"), email = 2: "richierocks@gmail.com"),
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/richierocks/pathological/issues/2
> .

## 

Regards,
Richie

Learning R http://shop.oreilly.com/product/0636920028352.do
4dpiecharts.com
