### ISSUE TITLE
why is the package not available for Windows?

### ISSUE THREAD

**Issue by maelle** [richierocks/pathological#7]
I've just noticed the package isn't available for Windows because I got an error with Appveyor CI -> is there any particular reason and will it stay unavailable? Thanks a lot!

**Comment by richierocks** [comment]
Sorry about this.  I had a little issue with a couple of the tests failing on the CRAN Windows machine.  (It was a bit obscure; I couldn't reproduce on my machine or AppVeyor or CRAN's Win Builder.) I'm hoping to get a fix pushed to CRAN tomorrow.

**Comment by maelle** [comment]
No problem, I just wondered whether it was gone for good (which would be sad). Thanks a lot!

**Comment by richierocks** [comment]
@masalmon Wow, that was harder than expected.  Sorry it took so long (it turns out that standardizing file paths in a cross-platform way is a dreadful nightmare).  The fixed version is on CRAN now, and the Windows binary should be available in the next day or two.

**Comment by maelle** [comment]
"it turns out that standardizing file paths in a cross-platform way is a dreadful nightmare" -> well congratulations and many thanks!!
