### ISSUE TITLE
documentation: standardize_path behavior for missing files

### ISSUE THREAD

**Issue by mmuurr** [richierocks/pathological#8]
`normalizePath` will alter its output for input paths where the file is missing, depending on the `mustWork` flag.
The `pathological::standardize_path` help page doesn't specify what to expect in these cases (though I believe the current behavior of returning the absolute path _as if_ the file were present is the preferable/best option).
Perhaps the docs should be updated to clarify the difference between `normalizePath` and `pathological::standardize_path` for this particular case?

(I'm happy to update the man page and submit a pull request if that's easiest for you.)

**Comment by mmuurr** [comment]
Update: there's actually a bug here, too.
In the example below, `missing.file` is, you guessed it, missing.
```R
!> standardize_path(c("missing.file", ".", "missing.file", "..", "missing.file"))
                          missing.file                                     .
            "/home/mmuurr/missing.file"                         "/home/mmuurr"
                          missing.file                                    ..
             "/home/mmuurr//home/mmuurr"                               "/home"
                          missing.file
            "/home/mmuurr/missing.file"
 Warning message:
 In x[ok][!is_absolute] <- file.path(getwd(), x[ok], fsep = "/") :
   number of items to replace is not a multiple of replacement length
```
Note that the second `missing.file` output is incorrect & inconsistent with the other `missing.file` outputs.

**Comment by richierocks** [comment]
@mmuurr Thanks for this; well spotted!
