### ISSUE TITLE
standardize_path inconsistency with relative path 'dots'

### ISSUE THREAD

**Issue by mmuurr** [richierocks/pathological#9]
`standarize_path` handles `.` and `..` path constructs differently depending on whether the specific file is actually present.
In the example below, `present.R` and `missing.R` are present and missing, respectively.
```
> standardize_path("./present.R")
"/the/path/to/present.R"

> standardize_path("./missing.R")
"/the/path/to/./missing.R"
```
Same results when using `..` in the input filepath.
Basically, if the file is present, the `.` and `..` characters are _replaced_ with the absolute path, while if the file is missing, the dots are _included_ in the (technically still valid) absolute path.

Perhaps this was intentional, though it's (at first) a bit unexpected and the docs would probably benefit from the description of this behavior.

**Comment by richierocks** [comment]
@mmuurr Again, well spotted! Thanks.
